namespace Compiler.Parsing.Syntax
{
    internal enum SyntaxKind
    {
        Invalid,

        BinaryExpression,
        UnaryExpression,
        IdentifierExpression,
        ConstantExpression,
        ReferenceExpression,
        MethodCallExpression,
        LambdaExpression,
        NewExpression,
        ArrayAccessExpression,
        UserDefinedTypeExpression,

        BoolKeyword,
        ByteKeyword,
        SByteKeyword,
        IntKeyword,
        UIntKeyword,
        ShortKeyword,
        UShortKeyword,
        LongKeyword,
        ULongKeyword,
        FloatKeyword,
        DoubleKeyword,
        DecimalKeyword,
        StringKeyword,
        //CharKeyword,
        //ObjectKeyword,
        VoidKeyword,

        ParameterDeclaration,
        VariableDeclaration,
        ClassDeclaration,
        FieldDeclaration,
        PropertyDeclaration,
        MethodDeclaration,
        ConstructorDeclaration,
        TypeDeclaration,
        ModuleDeclaration,

        BlockStatement,
        WhileStatement,
        IfStatement,
        ElseStatement,
        SwitchStatement,
        CaseStatement,
        ImportStatement,
        EmptyStatement,
        BreakStatement,
        ContinueStatement,
        ForStatement,
        ReturnStatement,
        SourceDocument,
        Attribute,
        EnumDeclaration,
        EnumMemberDeclaration,
        InterfaceDeclaration,
        InferredType,
        GenericTypeExpression,
    }
}
